### ISSUE TITLE
1.19 crash

### ISSUE THREAD

**Issue by Squeetsquib** [JamCoreModding/UtilityBelt#10]
crash when trying to use gui
https://imgur.com/a/fIBRiEr

also crashes when trying to remove item from belt slot.

mod version: utilitybelt-1.0.1
minecraft version: 1.19 (guessing the issue is that it was built for 1.19.2)
fabric version: 14.9

**Comment by Jamalam360** [comment]
Can you send `latest.log` from your logs folder please

**Comment by Squeetsquib** [comment]
https://pastebin.com/vmmjHX96

**Comment by Jamalam360** [comment]
Are the mods and versions identically on the server you're connecting to?

**Comment by Squeetsquib** [comment]
it should.

**Comment by Jamalam360** [comment]
It turned out to be an incredibly stupid issue on my part, but somewhat hard to diagnose. Thanks for reporting o7
