### ISSUE TITLE
allowed_in_utility_belt.json file in the mod has extra "_belt" in file name

### ISSUE THREAD

**Issue by floral-qua-floral** [JamCoreModding/UtilityBelt#11]
[`UtilityBelt/src/main/resources/data/utilitybelt/tags/items/allowed_in_utility_belt_belt.json`](https://github.com/JamCoreModding/UtilityBelt/blob/1.19.x/src/main/resources/data/utilitybelt/tags/items/allowed_in_utility_belt_belt.json) ends with `_belt_belt.json`, but it should be `_belt.json`. I noticed while setting up a datapack to add some items to the belt. When making a datapack, the file actually has to be named `allowed_in_utility_belt.json`, adding the extra `_belt` makes it not work. The issue is simply that the file packaged inside the mod is named incorrectly. If it were not empty, this would probably make it not function, but since the file doesn't actually add anything to the tag anyways this has no effect in-game.

**Comment by Jamalam360** [comment]
Thanks for reporting
