### ISSUE TITLE
When a tool being used from the hotbar breaks, the tool in the currently selected Utility Belt slot is deleted

### ISSUE THREAD

**Issue by floral-qua-floral** [JamCoreModding/UtilityBelt#4]
Reproducing the issue is pretty straightforward - get an item in the toolbelt, make sure the selected toolbelt slot is on that item, then switch to the normal hotbar and use a tool until it breaks. The item in the toolbelt will disappear, regardless of its durability.

I haven't checked yet whether this is a weird mod interaction, since that seemed unlikely. If you can't reproduce it, let me know and I'll do a more thorough investigation.

**Comment by Jamalam360** [comment]
Oh boy, more of these shenanigans

I'll investigate tomorrow, thanks
