### ISSUE TITLE
[Feature Request] Compatibility with Better Combat

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [JamCoreModding/UtilityBelt#6]
**MC** 1.19.2
**[BetterCombat](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)** 1.1.0
**UtilityBelt** 1.0.0

Currently, if you attempt to use anything, that is considered a weapon, from your utility belt, you perform a feint instead (a feature of Better Combat). You can still use tools that aren't considered weapons just fine.

Will also create an issue on BetterCombat's end in case it's something they can do on their side.

An example with a sword, just holding LMB to attack:

![2022-08-26_15 17 28](https://user-images.githubusercontent.com/86702831/186912963-851b7aec-17b1-4c30-a27c-a4aa3ea8dac3.png)

Logs, if necessary: https://gist.github.com/Footage2-Amply-Pounce/b110c3d394a5bb965fc7ed29101ec3d5

**Comment by Jamalam360** [comment]
Thank you, I'll look into it tonight

**Comment by Footage2-Amply-Pounce** [comment]
Tested on the new version of Better Combat, everything works as expected.

**Comment by Jamalam360** [comment]
Thanks
