### ISSUE TITLE
[Fabric] Crash on startup with Bedrockify

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [JamCoreModding/UtilityBelt#8]
**MC** 1.19.2
**FAPI** 0.60.0
**UtilityBelt** 1.0.1
**[Bedrockify](https://modrinth.com/mod/bedrockify)** 1.4.2

The crash only happens on Fabric, Quilt is unaffected.

Relevant log line:

`@Redirect conflict. Skipping utilitybelt.mixins.json:client.render.InGameHudMixin from mod utilitybelt->@Redirect::utilitybelt$disableHotbarHighlight(Lnet/minecraft/class_329;Lnet/minecraft/class_4587;IIIIII)V with priority 1000, already redirected by bedrockify.mixins.json:client.features.screenSafeArea.InGameHudMixin from mod bedrockify->@Redirect::drawTextureHotbar(Lnet/minecraft/class_329;Lnet/minecraft/class_4587;IIIIII)V with priority 1000`

Full logs: https://gist.github.com/Footage2-Amply-Pounce/45372f1b2f112b2e72b4a8d490393464

**Comment by Jamalam360** [comment]
Note to self: can be fixed with [this](https://github.com/LlamaLad7/MixinExtras/wiki/WrapWithCondition)

**Comment by Jamalam360** [comment]
Thank you for reporting o7
