### ISSUE TITLE
JamLib Error 

### ISSUE THREAD

**Issue by 3dguru** [JamCoreModding/UtilityBelt#9]
crash when loading minecraft 

starting minecraft gives error and wont load game 

https://pastebin.com/knRcPRsp

**Comment by Jamalam360** [comment]
Try updating JamLib

**Comment by Jamalam360** [comment]
Closing this as I'm 99% sure I suggested the correct solution, let me know if it's not solved o7

**Comment by 3dguru** [comment]
sorry for late reply, updated to jamlib 0.4.4 and appears to be working now  Thanks
